repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        args: [--safe, --quiet]
  - repo: local
    hooks:
      - id: pytest
        name: run tests with pytest
        language: system
        entry: poetry run pytest
        pass_filenames: false